### ISSUE TITLE
Empty with-blocks lead to runtime exceptions

### ISSUE THREAD

**Issue by FSharpCSharp** [anzwdev/ALWithUpdate#1]
When converting files with empty with-blocks, the conversion fails because an index is outside the valid range.
```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ALWithUpdate.WithRemoveSyntaxRewriter.ExpandWithStatements(SyntaxList`1 statements, SyntaxList`1& newStatements) in C:\Users\Administrator\source\repos\ALWithUpdate\ALWithUpdate\WithRemoveSyntaxRewriter.cs:Line 91.
   at ALWithUpdate.WithRemoveSyntaxRewriter.VisitBlock(BlockSyntax node) in C:\Users\Administrator\source\repos\ALWithUpdate\ALWithUpdate\WithRemoveSyntaxRewriter.cs:Line 24.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.BlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxNodes.Generated.cs:Line 23145.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:Line 29.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitMethodDeclaration(MethodDeclarationSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:Line 1873.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.MethodDeclarationSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxNodes.Generated.cs:Line 22850.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:Line 29.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:Line 146.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:Line 119.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitCodeunit(CodeunitSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:Line 162.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.CodeunitSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxNodes.Generated.cs:Line 1853.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:Line 29.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:Line 146.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:Line 119.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitObjectCompilationUnit(ObjectCompilationUnitSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:Line 22.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.ObjectCompilationUnitSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxNodes.Generated.cs:Line 66.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:Line 29.
   at ALWithUpdate.WithStatementsProjectConverter.ProcessALFile(String filePath, SyntaxTree syntaxTree, SemanticModel semanticModel) in C:\Users\Administrator\source\repos\ALWithUpdate\ALWithUpdate\WithStatementsProjectConverter.cs:Line 32.
   at ALWithUpdate.ProjectConverter.ProcessALFiles() in C:\Users\Administrator\source\repos\ALWithUpdate\ALWithUpdate\ProjectConverter.cs:Line 125.
   at ALWithUpdate.ProjectConverter.ConvertProject() in C:\Users\Administrator\source\repos\ALWithUpdate\ALWithUpdate\ProjectConverter.cs:Line 109.
   at ALWithUpdate.Program.Main(String[] args) in C:\Users\Administrator\source\repos\ALWithUpdate\ALWithUpdate\Program.cs:Line 46.
```

The following code unit can be used as a template to reproduce the problem:
```
codeunit 50100 MyCodeunit
{
    /* Event-Subscribers on Item Journal Line */

    [EventSubscriber(ObjectType::Table, Database::"Item Journal Line", 'OnAfterCopyItemJnlLineFromPurchHeader', '', false, false)]
    local procedure Handle_OnAfterCopyItemJnlLineFromPurchHeader(var ItemJnlLine: Record "Item Journal Line"; PurchHeader: Record "Purchase Header")
    begin
        with PurchHeader do begin
        end;
    end;

    /* Eventsubscribers on Purchase Header */

    [EventSubscriber(ObjectType::Table, Database::"Purchase Header", 'OnAfterInsertEvent', '', false, false)]
    local procedure Handle_OnAfterInsertPurchaseHeader(var Rec: Record "Purchase Header"; RunTrigger: Boolean)
    begin
        with Rec do begin
            if IsTemporary then
                exit;
            if RunTrigger then
                exit;
        end;
    end;

    [EventSubscriber(ObjectType::Table, Database::"Sales Header", 'OnAfterCopyShipToCustomerAddressFieldsFromShipToAddr', '', false, false)]
    local procedure Handle_OnAfterCopyShipToCustomerAddressFieldsFromShipToAddr(var SalesHeader: Record "Sales Header"; ShipToAddress: Record "Ship-to Address")
    begin
        with SalesHeader do begin
            "Bill-to Contact" := ShipToAddress.Name + ' ' + ShipToAddress."Name 2";
        end;
    end;

    [EventSubscriber(ObjectType::Table, Database::"Sales Header", 'OnAfterCopyShipToCustomerAddressFieldsFromCustomer', '', false, false)]
    local procedure Handle_OnAfterCopyShipToCustomerAddressFieldsFromCustomer(var SalesHeader: Record "Sales Header"; SellToCustomer: Record Customer)
    begin
        with SalesHeader do begin
            "Sell-to Contact" := SellToCustomer.Name + ' ' + SellToCustomer."Name 2";
        end;
    end;
}
```

Here is the error that occurs, and the corresponding location in the source code is also mentioned. Because the with-block is totally empty, the count is 0 and so is the corresponding array here.
https://github.com/anzwdev/ALWithUpdate/blob/d173bea9744109dc0c16c5825f170ed255c3823a/ALWithUpdate/WithRemoveSyntaxRewriter.cs#L91

**Comment by anzwdev** [comment]
Thank you for reporting the issue. I've updated the source code, it should work now.
